### ISSUE TITLE
Getting some warnings in the vue-countup-v2

### ISSUE THREAD

**Issue by theshashiverma** [xlsdg/vue-countup-v2#19]
npm WARN vue-countup-v2@4.0.0 requires a peer of countup.js@latest but none is installed. You must install peer dependencies yourself.
npm WARN vue-countup-v2@4.0.0 requires a peer of vue@latest but none is installed. You must install peer dependencies yourself.
Why i am getting this, I have the latest version of a library,.

**Comment by xlsdg** [comment]
`npm install --save vue countup.js vue-countup-v2`

**Comment by tsurumure** [comment]
When i use `yarn` I got this warning: 
```
warning " > vue-countup-v2@4.0.0" has incorrect peer dependency "countup.js@latest"
```

My version is:
```
"countup.js": "^2.0.4",
"vue-countup-v2": "^4.0.0"
```

any solution?

**Comment by xlsdg** [comment]
You can ignore that warning.

**Comment by mateuswetah** [comment]
Hey @xlsdg thank you for keeping this project!

While I agree that the warning can be ignored I would strongly suggest you to use a better dependency description here:
https://github.com/xlsdg/vue-countup-v2/blob/ae5b88db988b06ae47fdf18095d19649ae709548/package.json#L46

Because we are not entirely sure of how Vue and Countup projects may manage their releases in the future, it is really not safe to keep `@latest`.
